apiVersion: v1
kind: ServiceAccount
metadata:
  name: gsautomata-jobs
  namespace: giantswarm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gsautomata-jobs
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["infrastructure.giantswarm.io"]
  resources: ["awsclusters", "awscontrolplanes", "awsmachinedeployments"]
  verbs: ["get", "list"]
- apiGroups: ["application.giantswarm.io"]
  resources: ["apps"]
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gsautomata-jobs
subjects:
- kind: ServiceAccount
  name: gsautomata-jobs
  namespace: giantswarm
roleRef:
  kind: ClusterRole
  name: gsautomata-jobs
  apiGroup: rbac.authorization.k8s.io
